# Generated by Django 5.2.8 on 2025-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthyear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cast_crew',
            fields=[
                ('movie_cast_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('actor_id', models.IntegerField()),
                ('director_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='directors',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthyear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('plot', models.TextField()),
                ('runtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='watch_history',
            fields=[
                ('watched_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField()),
                ('watch_date', models.DateField()),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wrapped_summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('top_genre', models.CharField(max_length=100)),
                ('top_actor', models.CharField(max_length=100)),
                ('most_watched_movie', models.CharField(max_length=200)),
                ('total_movies_watched', models.IntegerField()),
            ],
        ),
    ]
