# Generated by Django 5.2.8 on 2025-11-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('movie_cast_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('plot', models.TextField()),
                ('runtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birthyear', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('watched_id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_date', models.DateField()),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='WrappedSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('top_genre', models.CharField(max_length=100)),
                ('top_actor', models.CharField(max_length=100)),
                ('most_watched_movie', models.CharField(max_length=200)),
                ('total_movies_watched', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='cast_crew',
        ),
        migrations.DeleteModel(
            name='movies',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='watch_history',
        ),
        migrations.DeleteModel(
            name='wrapped_summary',
        ),
        migrations.RenameModel(
            old_name='actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='directors',
            new_name='Director',
        ),
        migrations.AddField(
            model_name='castcrew',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='castcrew',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='castcrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
    ]
